steps:
- name: 'mcr.microsoft.com/dotnet/sdk:6.0'
  id: Unit Tests
  dir: 'hello-world-cpp'
  entrypoint: dotnet
  args: ['test', '--help']
- name: python
  id: Integration Tests and Endurance Tests
  dir: 'hello-world-cpp'
  entrypoint: pip
  args: ["debug", "--help"]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Build image
  dir: 'hello-world-cpp'
  entrypoint: gcloud
  args: ['builds', 'submit', '--tag', 'us-west2-docker.pkg.dev/g-lynnux/demo/viz:${SHORT_SHA}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Deploy
  dir: 'hello-world-cpp'
  entrypoint: bash
  args:
  - '-c'
  - |
    set -x && \
    export KUBECONFIG="$(pwd)/gateway-kubeconfig" && \
    gcloud container clusters get-credentials autopilot-cluster-1 --region us-west2 --project g-lynnux && \
    kubectl --kubeconfig gateway-kubeconfig create deployment viz --image=us-west2-docker.pkg.dev/g-lynnux/demo/viz:${SHORT_SHA}
    #sed -i 's/\$$IMAGE_TAG/${SHORT_SHA}/g' kubernetes/atlas2-deployment.yaml && \
    #kubectl apply -f kubernetes
