steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'hello-world-dotnet'
  entrypoint: gcloud
  id: Build image
  args: ['builds', 'submit', '--tag', 'us-west2-docker.pkg.dev/g-lynnux/cloud-run-source-deploy/hello-world-dotnet:${SHORT_SHA}']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'hello-world-dotnet'
  entrypoint: gcloud
  id: Deploy
  args: ['run', 'deploy', 'hello-world-dotnet', '--image', 'us-west2-docker.pkg.dev/g-lynnux/cloud-run-source-deploy/hello-world-dotnet:${SHORT_SHA}', '--region=us-west2', '--no-allow-unauthenticated']
