steps:
### build and deploy with cloud run ###
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  dir: 'hello-world-dotnet'
  entrypoint: gcloud
  id: Deploy
  args: ['run', 'deploy', 'hello-world-dotnet', '--source', '.', '--region=us-west2', '--no-allow-unauthenticated']

### build with buildpack and deploy to gke ###
