steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'ace-test-py-function', '--source=.', '--trigger-http', '--runtime=python312']
  options:
    logging: CLOUD_LOGGING_ONLY
