steps:
- name: 'gcr.io/cloud-builders/gcloud'
  dir: 'hello-world-py'
  args: ['functions', 'deploy', 'ace-test-py-function', '--source=.', '--trigger-http', '--runtime=python312']
options:
  logging: CLOUD_LOGGING_ONLY
