apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: atlas2
  name: atlas2
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.99.1.221
  clusterIPs:
  - 10.99.1.221
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32488
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: atlas2
  sessionAffinity: None
  type: LoadBalancer
